/**
 * Root Layout Component
 * Wraps entire application with metadata and global styles
 * Sets up fonts and basic HTML structure
 */
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Import and configure Geist fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Application metadata
export const metadata: Metadata = {
  title: "Car Management System",
  description: "Generated by Car Management System",
};

/**
 * Root Layout - Main application wrapper
 * @param children - Child components/pages
 */
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="mdl-js">{children}</body>
    </html>
  );
}

